DELIMITER $$

DROP PROCEDURE IF EXISTS sp1;

CREATE PROCEDURE sp1 (DB NVARCHAR(12))
BEGIN
	SELECT CONCAT('ALTER TABLE `', TABLE_SCHEMA, '`.`', TABLE_NAME, '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;')
	FROM information_schema.TABLES
	WHERE TABLE_SCHEMA = DB
	UNION
	SELECT CONCAT('ALTER TABLE `', TABLE_SCHEMA, '`.`', TABLE_NAME, '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;')
	FROM information_schema.TABLES
	WHERE TABLE_SCHEMA = DB
	UNION
	SELECT CONCAT('ALTER TABLE `', TABLE_SCHEMA, '`.`', TABLE_NAME, '` CHANGE COLUMN `', COLUMN_NAME, '` `', COLUMN_NAME, '` VARCHAR(', CHARACTER_MAXIMUM_LENGTH, ') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;') 
	FROM information_schema.COLUMNS 
	WHERE TABLE_SCHEMA = DB
		AND DATA_TYPE = 'varchar';
END;
$$

DELIMITER ;

call sp1('lab_school');